name: Build RouteConfigurator Rootless Deb
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 安装编译依赖
        run: |
          sudo apt update
          sudo apt install -y git make curl libxml2-dev zip unzip clang lld xz-utils

      - name: 一键安装完整Theos+Linux交叉工具链
        run: |
          export THEOS=$HOME/theos
          rm -rf $THEOS
          curl -L https://raw.githubusercontent.com/theos/theos/master/install -o install.sh
          chmod +x install.sh
          bash install.sh --linux
          rm -f install.sh
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: 下载官方 iPhoneOS15.6 SDK
        run: |
          export THEOS=$HOME/theos
          rm -rf $THEOS/sdks
          mkdir -p $THEOS/sdks
          curl -L -o sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS15.6.sdk.tar.xz
          tar -xf sdk.tar.xz -C $THEOS/sdks/
          rm -f sdk.tar.xz

      - name: 编译 rootless 插件（跳过make clean）
        run: |
          export THEOS=$HOME/theos
          make package NO_CLEAN=1

      - name: 上传deb安装包
        uses: actions/upload-artifact@v4
        with:
          path: ./packages/*.deb
          name: RouteConfigurator-Rootless-Deb
