name: Build RouteConfigurator Tweak
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 使用内置完整Theos、多版本iOS SDK的镜像
    container: ghcr.io/roothub-lab/theos:latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v5

      - name: Compile rootless deb
        run: make package THEOS_PACKAGE_SCHEME=rootless

      - name: Upload deb installer
        uses: actions/upload-artifact@v4
        with:
          name: RouteConfigurator-Deb
          path: packages/*.deb
