name: Build RouteConfigurator
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install basic build tools
        run: |
          sudo apt update
          sudo apt install -y git make clang perl dpkg-dev

      - name: Setup Theos & SDK
        run: |
          export THEOS=$HOME/theos
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH
          # 清理旧文件夹，防止冲突
          rm -rf $THEOS
          rm -rf $THEOS/sdks
          # 拉取theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          # 备用方案：用git获取ldid，绕过github下载超时/404
          git clone https://github.com/sbingner/ldid.git /tmp/ldid
          cd /tmp/ldid
          git checkout v2.1.2
          make linux
          cp ldid $THEOS/bin/
          chmod +x $THEOS/bin/ldid
          # 拉取SDK
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build rootless deb
        run: make package THEOS_PACKAGE_SCHEME=rootless

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: RouteConfigurator-deb
          path: packages/*.deb
